model_name: A2C_RE3 # [A2C, A2C_DP, A2C_ICM, A2C_NOISE, A2C_RE3]
random_seed: 42
device: 0 # GPU 0,1,..., or CPU
stack_size: 5 # channel image size to CNN is (stack_size, 84, 84)
save_dir: exp
save_frequency: 5000 # save pt files
steps_per_update: 5 # Max number of forward steps for A3C before update
num_of_steps: 250000 # Number of training steps
num_of_processes: 8 # processes

clip_grad:  0.5 # [False or float]
lr: 0.0001 # optimizer learning rate